const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const stages=['전체','Kinetic Field','Circuit Grounds','Stereo Bloom','Bionic Jungle','BoomBox ART CAR'];
let date='2026-10-03',stage='전체',mine=false,query='',lang='ko';
let fav=new Set(JSON.parse(localStorage.getItem('edcFavs')||'[]'));
const stageClass={'Kinetic Field':'kinetic','Circuit Grounds':'circuit','Stereo Bloom':'stereo','Bionic Jungle':'bionic','BoomBox ART CAR':'boom'};
function mins(t){let [h,m]=t.split(':').map(Number);return (h<5?h+24:h)*60+m}
function initials(n){return n.replace(/[^A-Za-z0-9가-힣Øø]/g,' ').trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'DJ'}
function filtered(){return SHOWS.filter(x=>x.date===date&&(stage==='전체'||x.stage===stage)&&(!mine||fav.has(String(x.id)))&&(!query||x.artist.toLowerCase().includes(query.toLowerCase())))}
function renderStages(){$('#stages').innerHTML=stages.map(s=>`<button class="${s===stage?'active':''}" data-stage="${s}">${s}</button>`).join('');$$('#stages button').forEach(b=>b.onclick=()=>{stage=b.dataset.stage;render()})}
function card(x){let on=fav.has(String(x.id));return `<article class="card ${on?'active':''}" data-id="${x.id}"><div class="photo">${initials(x.artist)}</div><div><h3>${x.artist}</h3><div class="meta"><span class="stage-name">${x.stage}</span> · ${x.start} — ${x.end}</div></div><button class="star ${on?'on':''}" data-fav="${x.id}">${on?'★':'☆'}</button></article>`}
function render(){renderStages();let data=filtered();$('#sets').textContent=data.length;$('#count').textContent=fav.size;let groups={};data.sort((a,b)=>mins(a.start)-mins(b.start)||a.stage.localeCompare(b.stage)).forEach(x=>(groups[x.start]??=[]).push(x));$('#timeline').innerHTML=Object.entries(groups).map(([t,items])=>`<section class="time-group"><div class="time-label">${t}</div>${items.map(card).join('')}</section>`).join('')||'<div class="extra-card">조건에 맞는 공연이 없습니다.</div>';$$('[data-id]').forEach(c=>c.onclick=e=>{if(e.target.closest('[data-fav]'))return;openShow(Number(c.dataset.id))});$$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav)});$('#posterImg').src=date==='2026-10-03'?'assets/edc-2026-10-03.jpg':'assets/edc-2026-10-04.jpg')}
function toggleFav(id){id=String(id);fav.has(id)?fav.delete(id):fav.add(id);localStorage.setItem('edcFavs',JSON.stringify([...fav]));render()}
function openShow(id){let x=SHOWS.find(a=>a.id===id);$('#mphoto').textContent=initials(x.artist);$('#mstage').textContent=x.stage;$('#martist').textContent=x.artist;$('#mtime').textContent=`${x.start} — ${x.end} · ${x.date.slice(5).replace('-','/')}`;$('#yt').href='https://www.youtube.com/results?search_query='+encodeURIComponent(x.artist);$('#sp').href='https://open.spotify.com/search/'+encodeURIComponent(x.artist);$('#mfav').textContent=fav.has(String(id))?'★ 내 일정에서 제거':'☆ 내 일정에 추가';$('#mfav').onclick=()=>{toggleFav(id);openShow(id)};$('#modal').classList.add('open')}
function closeAll(){$$('.modal').forEach(m=>m.classList.remove('open'))}
function conflicts(){let selected=SHOWS.filter(x=>fav.has(String(x.id)));let bad=[];for(let i=0;i<selected.length;i++)for(let j=i+1;j<selected.length;j++){let a=selected[i],b=selected[j];if(a.date===b.date&&mins(a.start)<mins(b.end)&&mins(b.start)<mins(a.end))bad.push([a,b])}return bad}
function showConflicts(){let c=conflicts();$('#infoTitle').textContent='동선 겹침 계산';$('#infoBody').innerHTML=c.length?`<p class="muted">선택한 공연 중 시간이 겹치는 조합 ${c.length}개를 찾았습니다.</p>`+c.map(([a,b])=>`<div class="info-row"><span>${a.artist}<br><small>${a.stage} · ${a.start}-${a.end}</small></span><b>↔</b><span>${b.artist}<br><small>${b.stage} · ${b.start}-${b.end}</small></span></div>`).join(''):'<p>현재 선택한 공연 사이에 겹치는 시간이 없습니다.</p>';$('#infoModal').classList.add('open')}
function ranking(){let counts={};fav.forEach(id=>{let x=SHOWS.find(a=>String(a.id)===id);if(x)counts[x.artist]=(counts[x.artist]||0)+1});let arr=Object.entries(counts).sort((a,b)=>b[1]-a[1]);$('#infoTitle').textContent='내 DJ 랭킹';$('#infoBody').innerHTML=arr.length?arr.map((x,i)=>`<div class="rank"><span>${i+1}. ${x[0]}</span><b>★ ${x[1]}</b></div>`).join(''):'<p class="muted">아직 내 일정에 DJ를 추가하지 않았습니다.</p>';$('#infoModal').classList.add('open')}
function wallpaper(){let c=$('#wallCanvas'),ctx=c.getContext('2d'),items=SHOWS.filter(x=>fav.has(String(x.id))).sort((a,b)=>mins(a.start)-mins(b.start));let g=ctx.createLinearGradient(0,0,1080,1920);g.addColorStop(0,'#18063d');g.addColorStop(.5,'#32108a');g.addColorStop(1,'#080314');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#fff';ctx.font='900 76px Arial';ctx.fillText('EDC KOREA',70,150);ctx.font='700 46px Arial';ctx.fillStyle='#58f3ff';ctx.fillText(date==='2026-10-03'?'SATURDAY · OCTOBER 3':'SUNDAY · OCTOBER 4',70,220);ctx.font='700 30px Arial';let y=310;items.filter(x=>x.date===date).forEach(x=>{ctx.fillStyle='#ff39aa';ctx.fillRect(70,y-32,18,55);ctx.fillStyle='#fff';ctx.font='700 32px Arial';ctx.fillText(`${x.start}  ${x.artist}`,105,y);ctx.font='20px Arial';ctx.fillStyle='#bdb2d8';ctx.fillText(x.stage,105,y+30);y+=90});if(!items.length){ctx.fillStyle='#fff';ctx.font='34px Arial';ctx.fillText('⭐ 내 일정에 DJ를 추가해 주세요',70,350)}}
$$('.day').forEach(b=>b.onclick=()=>{$$('.day').forEach(x=>x.classList.remove('active'));b.classList.add('active');date=b.dataset.date;render()});$('#search').oninput=e=>{query=e.target.value;render()};$('#mine').onclick=()=>{mine=!mine;$('#mine').style.borderColor=mine?'#8c6bff':'';render()};$('#wallpaper').onclick=()=>{$('#wallModal').classList.add('open');wallpaper()};$('#downloadWall').onclick=()=>{let a=document.createElement('a');a.download=`edc-korea-${date}-my-timetable.png`;a.href=$('#wallCanvas').toDataURL('image/png');a.click()};$('#conflict').onclick=showConflicts;$('#conflict2').onclick=showConflicts;$('#ranking').onclick=ranking;$('#posterBtn').onclick=()=>{$('#wallModal').classList.add('open');let c=$('#wallCanvas');c.width=1080;c.height=1920;let ctx=c.getContext('2d');ctx.fillStyle='#070414';ctx.fillRect(0,0,c.width,c.height);let im=new Image();im.onload=()=>{let r=Math.min(c.width/im.width,c.height/im.height);let w=im.width*r,h=im.height*r;ctx.drawImage(im,(c.width-w)/2,(c.height-h)/2,w,h)};im.src=$('#posterImg').src}};$('#close').onclick=closeAll;$('#wallClose').onclick=closeAll;$('#infoClose').onclick=closeAll;$$('.shade').forEach(x=>x.onclick=closeAll);$('#lang').onclick=()=>{lang=lang==='ko'?'en':'ko';document.documentElement.lang=lang;$('#subtitle').textContent=lang==='en'?'Tap a set for details.':'공연 카드를 눌러 상세 정보를 확인하세요.'};
render();
